### ISSUE TITLE
Fluid tanks don't accept milk

### ISSUE THREAD

**Issue by Philosoph42** [Kotori316/FluidTank2#3]
Fluid tanks can't be filled with milk by right clicking with milk bucket.
Mod set used for test:
fabric loader 0.14.21-1.20.1
fabric-api-0.85.0+1.20.1
largefluidtank-fabric-20.4.1
sclable-ctas-force-fabric-2.1.0

**Comment by Kotori316** [comment]
For fabric version, it's intended. I have no plan to support vanilla milk because no one provides the standard implementation of the fluid "milk".
(The screenshot was taken in forge version, so I should change it to new version.)

The solution is to install mod that enables to treat Milk as fluids like Water and Lava, such as [this mod](https://modrinth.com/mod/milk_plus).
As long as I read the code, milk_plus mod will do perfect job.
