### ISSUE TITLE
Modpack Permission Request

### ISSUE THREAD

**Issue by Kasax007** [Kotori316/FluidTank2#6]
Hey Kotori, for uploading a modpack on modrinth and to include any mod, I must ask for permission to include them. I would love to include your mod in my pack since it is a great way to store a lot of fluids. Therefore I would love to get permission to include your amazing mod in my modpack. If there is any further information you require I am happy to help!
Best regards,
Kasax

**Comment by Kotori316** [comment]
This issue was transferred because you posted to wrong repository.
Versions of FluidTank on Modrinth are hosted on this repository, not the old one.

Feel free to share my mods via modpacks, but please follow the MIT License. (Maybe I should upload the license and update the description on Modrinth)
